octopus:
  environments:
  - development
  - production
  development:
    shard_one:
      host: 192.168.0.105
      adapter: mysql2
      username: jarlio
      password: Raven
      database: skyline_development
    shard_two:
      host: 192.168.0.102
      adapter: mysql2
      username: root
      password:
      database: skyline_development
  production:
    shard_one:
      host: localhost
      adapter: mysql
      database: app_production